#!/bin/bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the MIT License. See the LICENSE accompanying this file
# for the specific language governing permissions and limitations under
# the License.

INTERFACE=eth2
ACTION=remove
HWADDR=41:b0:34:f0:ac:bd

. ../ec2net-functions
. ./test-functions

deactivate_primary
unplug_interface
